/**
 * ============================================================================
 *  MOCK DATA — NOT FROM WIX.
 *  Used only when WIX_CLIENT_ID is unset, so the storefront builds, renders
 *  and can be SEO-audited without a Wix site. Shapes mirror what the Wix
 *  provider returns. Images are local SVG placeholders in /public/mock-media
 *  (generated by scripts/gen-mock-media.mjs).
 *  The UI shows a "demo data" notice and responses carry `X-Data-Source: mock`.
 * ============================================================================
 */
import type { Collection, Product } from '#/lib/types'
import type { CatalogProvider } from './provider'
import { ALL_PRODUCTS_COLLECTION_ID } from './provider'

const COLLECTIONS: Array<Collection> = [
  {
    id: ALL_PRODUCTS_COLLECTION_ID,
    slug: 'all-products',
    name: 'All Products',
    isAllProducts: true,
    description: 'Browse our complete catalog of apparel, home goods and accessories.',
  },
  {
    id: 'c-apparel',
    slug: 'apparel',
    name: 'Apparel',
    description: 'Organic cotton tees, merino knits and outerwear built to last for years.',
  },
  {
    id: 'c-home',
    slug: 'home-goods',
    name: 'Home Goods',
    description: 'Stoneware, linens and small-batch candles to make every room feel calm.',
  },
  {
    id: 'c-accessories',
    slug: 'accessories',
    name: 'Accessories',
    description: 'Leather goods, bags and everyday carry essentials, made in small runs.',
  },
]

const SEED: Array<[string, string, number, string, string?]> = [
  // [name, collection, price, adjective, ribbon]
  ['Organic Cotton Crew Tee', 'c-apparel', 32, 'breathable', 'Bestseller'],
  ['Merino Wool Sweater', 'c-apparel', 128, 'warm'],
  ['Waxed Canvas Jacket', 'c-apparel', 245, 'weatherproof', 'New'],
  ['Linen Button-Down Shirt', 'c-apparel', 89, 'airy'],
  ['Heavyweight Hoodie', 'c-apparel', 95, 'cozy'],
  ['Relaxed Chino Pants', 'c-apparel', 78, 'versatile'],
  ['Ribbed Beanie', 'c-apparel', 28, 'soft'],
  ['Selvedge Denim Jeans', 'c-apparel', 165, 'rugged'],
  ['Quilted Vest', 'c-apparel', 110, 'lightweight'],
  ['Striped Breton Top', 'c-apparel', 58, 'classic'],
  ['Wool Overshirt', 'c-apparel', 138, 'layerable'],
  ['Everyday Shorts', 'c-apparel', 54, 'easygoing'],
  ['Stoneware Mug Set', 'c-home', 44, 'handmade', 'Bestseller'],
  ['Linen Duvet Cover', 'c-home', 210, 'stonewashed'],
  ['Soy Wax Candle', 'c-home', 26, 'hand-poured'],
  ['Ceramic Planter', 'c-home', 38, 'glazed'],
  ['Wool Throw Blanket', 'c-home', 145, 'heirloom'],
  ['Walnut Serving Board', 'c-home', 68, 'oiled'],
  ['Cotton Waffle Towels', 'c-home', 52, 'absorbent'],
  ['Glass Carafe', 'c-home', 34, 'mouth-blown'],
  ['Linen Napkins (Set of 4)', 'c-home', 36, 'washed'],
  ['Brass Table Lamp', 'c-home', 189, 'warm-toned', 'New'],
  ['Full-Grain Leather Wallet', 'c-accessories', 65, 'slim'],
  ['Canvas Tote Bag', 'c-accessories', 42, 'sturdy'],
  ['Leather Belt', 'c-accessories', 58, 'vegetable-tanned'],
  ['Weekender Duffel', 'c-accessories', 225, 'spacious'],
  ['Cashmere Scarf', 'c-accessories', 120, 'featherlight'],
  ['Everyday Backpack', 'c-accessories', 148, 'water-resistant'],
  ['Key Organizer', 'c-accessories', 24, 'compact'],
  ['Sunglasses', 'c-accessories', 98, 'polarized'],
]

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/\(.*?\)/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}

const usd = (n: number) =>
  new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(n)

export const MOCK_PRODUCTS: Array<Product> = SEED.map(
  ([name, collectionId, price, adjective, ribbon], i) => {
    const slug = slugify(name)
    const onSale = i % 7 === 3
    const salePrice = onSale ? Math.round(price * 0.8) : undefined
    const outOfStock = i % 11 === 9
    const collectionName = COLLECTIONS.find((c) => c.id === collectionId)!.name
    const text = `Our ${adjective} ${name.toLowerCase()} is made in small batches from responsibly sourced materials. Designed to be used every day and built to last, it ships free on orders over $75 with 30-day returns.`
    return {
      id: `mock-${String(i + 1).padStart(3, '0')}`,
      slug,
      name,
      descriptionHtml: `<p>${text}</p><ul><li>Responsibly sourced materials</li><li>Small-batch production</li><li>Free returns within 30 days</li></ul>`,
      descriptionText: text,
      sku: `WSS-${String(1000 + i)}`,
      brand: 'Wix SEO Store',
      currency: 'USD',
      price,
      salePrice,
      formattedPrice: usd(price),
      formattedSalePrice: salePrice ? usd(salePrice) : undefined,
      availability: outOfStock ? 'OutOfStock' : 'InStock',
      inStock: !outOfStock,
      images: [0, 1].map((v) => ({
        src: `/mock-media/${slug}-${v + 1}.svg`,
        width: 1200,
        height: 1200,
        alt: v === 0 ? `${name} — ${collectionName}` : `${name}, alternate view`,
      })),
      collectionIds: [ALL_PRODUCTS_COLLECTION_ID, collectionId],
      updatedAt: new Date(Date.UTC(2026, 8, 1 + (i % 28), 12)).toISOString(),
      ribbon,
    }
  },
)

export const MOCK_COLLECTIONS: Array<Collection> = COLLECTIONS.map((c) => ({
  ...c,
  image: {
    src: `/mock-media/collection-${c.slug}.svg`,
    width: 1200,
    height: 1200,
    alt: `${c.name} collection`,
  },
}))

export function createMockProvider(): CatalogProvider {
  return {
    source: 'mock',
    listCollections: async () => MOCK_COLLECTIONS,
    getCollectionBySlug: async (slug) =>
      MOCK_COLLECTIONS.find((c) => c.slug === slug) ?? null,
    listProducts: async ({ collectionId, limit, offset }) => {
      const all = collectionId
        ? MOCK_PRODUCTS.filter((p) => p.collectionIds.includes(collectionId))
        : MOCK_PRODUCTS
      return { items: all.slice(offset, offset + limit), total: all.length }
    },
    getProductBySlug: async (slug) => MOCK_PRODUCTS.find((p) => p.slug === slug) ?? null,
    searchProducts: async (query, limit) => {
      const q = query.toLowerCase()
      return MOCK_PRODUCTS.filter((p) => p.name.toLowerCase().includes(q)).slice(0, limit)
    },
    listAllProductsForSitemap: async () =>
      MOCK_PRODUCTS.map((p) => ({
        slug: p.slug,
        updatedAt: p.updatedAt,
        collectionIds: p.collectionIds,
      })),
  }
}
