// Curated demo catalog.
//
// The storefront always prefers *live* data read from Base44 (see store.ts).
// This dataset is the graceful fallback that renders when there is no live data
// yet — during local `astro dev` (no Base44 runtime), and right after a fresh
// deploy before the Product/Category entities have been seeded. It keeps the
// showcase looking like a real store at all times. IDs are stable slugs so the
// demo Reviews line up with the demo Products.

import type { Category, Product, Review } from "./types";

export const DEMO_CATEGORIES: Category[] = [
  {
    id: "single-origin",
    name: "Single-Origin",
    slug: "single-origin",
    description:
      "Traceable lots from a single farm or region, roasted to highlight what makes each origin sing.",
  },
  {
    id: "blends",
    name: "Signature Blends",
    slug: "blends",
    description:
      "Balanced, repeatable house recipes built for everyday brewing and pulling shots.",
  },
  {
    id: "decaf",
    name: "Decaf",
    slug: "decaf",
    description:
      "All of the flavour, none of the buzz — gently decaffeinated with the Swiss Water process.",
  },
  {
    id: "gear",
    name: "Brewing Gear",
    slug: "gear",
    description:
      "The kit we reach for every morning: drippers, kettles, grinders and mugs.",
  },
];

export const DEMO_PRODUCTS: Product[] = [
  {
    id: "ethiopia-yirgacheffe",
    name: "Ethiopia Yirgacheffe",
    slug: "ethiopia-yirgacheffe",
    description:
      "Delicate and tea-like, with jasmine aromatics, bergamot and a wash of stone fruit. Our brightest single-origin — beautiful as a pour-over.",
    price: 22,
    currency: "USD",
    category_id: "single-origin",
    stock: 24,
    featured: true,
    tags: ["floral", "fruity", "filter"],
    status: "active",
    origin: "Yirgacheffe, Ethiopia",
    roast_level: "light",
    accent: "#c26b3f",
  },
  {
    id: "colombia-huila",
    name: "Colombia Huila",
    slug: "colombia-huila",
    description:
      "Round and comforting: red apple, caramel and a soft cocoa finish. The crowd-pleaser that works in any brewer.",
    price: 20,
    currency: "USD",
    category_id: "single-origin",
    stock: 40,
    featured: false,
    tags: ["balanced", "caramel"],
    status: "active",
    origin: "Huila, Colombia",
    roast_level: "medium",
    accent: "#a8552b",
  },
  {
    id: "sumatra-mandheling",
    name: "Sumatra Mandheling",
    slug: "sumatra-mandheling",
    description:
      "Deep and syrupy, with cedar, dark chocolate and a savoury earthiness. Low acidity and endlessly cosy.",
    price: 21,
    currency: "USD",
    category_id: "single-origin",
    stock: 18,
    featured: false,
    tags: ["earthy", "chocolate", "bold"],
    status: "active",
    origin: "Lintong, Sumatra",
    roast_level: "dark",
    accent: "#5b4632",
  },
  {
    id: "sunrise-blend",
    name: "Sunrise Blend",
    slug: "sunrise-blend",
    description:
      "Our morning staple — a bright yet balanced cup of milk chocolate, orange and toasted almond. Great in a drip machine.",
    price: 18,
    currency: "USD",
    category_id: "blends",
    stock: 60,
    featured: true,
    tags: ["everyday", "balanced"],
    status: "active",
    origin: "Blend of Latin America & East Africa",
    roast_level: "medium",
    accent: "#d08b3c",
  },
  {
    id: "midnight-oil-espresso",
    name: "Midnight Oil Espresso",
    slug: "midnight-oil-espresso",
    description:
      "Built for the machine: thick crema, dark chocolate, molasses and a plummy sweetness that stands up to milk.",
    price: 19,
    currency: "USD",
    category_id: "blends",
    stock: 52,
    featured: true,
    tags: ["espresso", "chocolate", "bold"],
    status: "active",
    origin: "Blend of Brazil & Sumatra",
    roast_level: "medium-dark",
    accent: "#3f5f52",
  },
  {
    id: "house-blend",
    name: "House Blend",
    slug: "house-blend",
    description:
      "The one we drink all day. Approachable, smooth and nutty with a clean finish — nothing to prove, everything to love.",
    price: 17,
    currency: "USD",
    category_id: "blends",
    stock: 75,
    featured: false,
    tags: ["everyday", "smooth"],
    status: "active",
    origin: "Blend of Latin America",
    roast_level: "medium",
    accent: "#b06a34",
  },
  {
    id: "swiss-water-decaf",
    name: "Swiss Water Decaf",
    slug: "swiss-water-decaf",
    description:
      "A chemical-free decaf with real body: brown sugar, baked apple and a whisper of hazelnut. Nobody will guess.",
    price: 19,
    currency: "USD",
    category_id: "decaf",
    stock: 30,
    featured: false,
    tags: ["decaf", "smooth"],
    status: "active",
    origin: "Colombia",
    roast_level: "medium",
    accent: "#6d8a7a",
  },
  {
    id: "decaf-espresso",
    name: "Decaf Espresso",
    slug: "decaf-espresso",
    description:
      "An after-dinner shot with no compromises — dark cocoa, dried fig and a lingering sweetness.",
    price: 19,
    currency: "USD",
    category_id: "decaf",
    stock: 22,
    featured: false,
    tags: ["decaf", "espresso"],
    status: "active",
    origin: "Blend of Colombia & Brazil",
    roast_level: "medium-dark",
    accent: "#4d6156",
  },
  {
    id: "pour-over-kit",
    name: "Pour-Over Starter Kit",
    slug: "pour-over-kit",
    description:
      "Everything for a clean, sweet filter cup: a ceramic dripper, 50 filters and a step-by-step brew card. Just add a kettle.",
    price: 34,
    currency: "USD",
    category_id: "gear",
    stock: 35,
    featured: true,
    tags: ["gear", "gift"],
    status: "active",
    accent: "#c98a4b",
  },
  {
    id: "gooseneck-kettle",
    name: "Gooseneck Kettle",
    slug: "gooseneck-kettle",
    description:
      "A precise pour, every time. Matte-black stainless steel with a counterbalanced spout for total control.",
    price: 68,
    currency: "USD",
    category_id: "gear",
    stock: 14,
    featured: false,
    tags: ["gear"],
    status: "active",
    accent: "#3a3a3a",
  },
  {
    id: "conical-burr-grinder",
    name: "Conical Burr Grinder",
    slug: "conical-burr-grinder",
    description:
      "Uniform grounds from espresso to French press, with 30 stepped settings and a stainless burr set that lasts.",
    price: 95,
    currency: "USD",
    category_id: "gear",
    stock: 9,
    featured: true,
    tags: ["gear", "premium"],
    status: "active",
    accent: "#7a5c3e",
  },
  {
    id: "ceramic-mug-set",
    name: "Ceramic Mug (Set of 2)",
    slug: "ceramic-mug-set",
    description:
      "Hand-glazed 10oz tumblers that keep coffee warmer for longer. Sold as a pair, because coffee is better shared.",
    price: 28,
    currency: "USD",
    category_id: "gear",
    stock: 48,
    featured: false,
    tags: ["gear", "gift"],
    status: "active",
    accent: "#9a8f7f",
  },
];

export const DEMO_REVIEWS: Review[] = [
  {
    id: "rev-1",
    product_id: "ethiopia-yirgacheffe",
    rating: 5,
    title: "The best filter coffee I've made at home",
    body: "Floral and clean, exactly as described. I brew it as a V60 every morning and it never gets old.",
    author_name: "Priya R.",
    created_date: "2026-05-20T08:12:00Z",
  },
  {
    id: "rev-2",
    product_id: "ethiopia-yirgacheffe",
    rating: 4,
    title: "Lovely, if a little delicate",
    body: "Gorgeous aromatics. If you like bold dark roasts this might read as light, but for me it's perfect.",
    author_name: "Marcus L.",
    created_date: "2026-05-28T17:40:00Z",
  },
  {
    id: "rev-3",
    product_id: "sunrise-blend",
    rating: 5,
    title: "My default reorder",
    body: "Balanced and reliable. Works great in my drip machine and my partner (a self-described coffee snob) approves.",
    author_name: "Dana K.",
    created_date: "2026-06-02T06:55:00Z",
  },
  {
    id: "rev-4",
    product_id: "midnight-oil-espresso",
    rating: 5,
    title: "Cracking espresso",
    body: "Thick crema and holds up beautifully in a flat white. This is a permanent fixture in my kitchen now.",
    author_name: "Tomás V.",
    created_date: "2026-06-10T15:22:00Z",
  },
  {
    id: "rev-5",
    product_id: "conical-burr-grinder",
    rating: 4,
    title: "Big upgrade from a blade grinder",
    body: "Consistent grounds and much quieter than I expected. The dial-in for espresso took a couple of tries.",
    author_name: "Elena F.",
    created_date: "2026-06-15T11:03:00Z",
  },
  {
    id: "rev-6",
    product_id: "pour-over-kit",
    rating: 5,
    title: "Perfect gift",
    body: "Bought it for my brother who's getting into coffee. The brew card made it totally approachable for him.",
    author_name: "Sam W.",
    created_date: "2026-06-21T09:30:00Z",
  },
];
